version: '3'
services:
  postgres:
    image: postgres:14.4
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q --dbname=${POSTGRES_DB} --username=${POSTGRES_USER}
      interval: 2s
      timeout: 2s
      retries: 5

  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_volume:
  static_volume: