version: '3'
services:
  postgres:
    image: postgres:14.4
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q --dbname=${POSTGRES_DB} --username=${POSTGRES_USER}
      interval: 2s
      timeout: 2s
      retries: 5

#  backend:
#    container_name: django
#    build:
#      context: .
#    volumes:
#      - static_volume:/app/static
#    depends_on:
#      - db
#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx/sites.conf:/etc/nginx/conf.d/default.conf:ro
#      - static_volume:/data/static:ro
#    depends_on:
#      - backend
#    ports:
#      - "8000:80"

volumes:
  postgres_volume:
  #static_volume: